// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg1j4E-BKgqkwVvL-rlTSsWI8R0NWpcW8',
    appId: '1:668044338773:android:46e15ab3150a6f9beb56dc',
    messagingSenderId: '668044338773',
    projectId: 'bhagavad-gita-52312',
    storageBucket: 'bhagavad-gita-52312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgRmzEoMt_tXgEYPwTCW7h9QVthjh3IQI',
    appId: '1:668044338773:ios:cb3683498f17e021eb56dc',
    messagingSenderId: '668044338773',
    projectId: 'bhagavad-gita-52312',
    storageBucket: 'bhagavad-gita-52312.firebasestorage.app',
    iosClientId: '668044338773-v0eddbgaiflp9j9o9g6e5v20j2amg02u.apps.googleusercontent.com',
    iosBundleId: 'com.antigravity.emotionGita',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3UALsv2Ve4D-hRoOceZmJq1aE_1__kiI',
    appId: '1:668044338773:web:3901aecf36195723eb56dc',
    messagingSenderId: '668044338773',
    projectId: 'bhagavad-gita-52312',
    authDomain: 'bhagavad-gita-52312.firebaseapp.com',
    storageBucket: 'bhagavad-gita-52312.firebasestorage.app',
    measurementId: 'G-54S4E6TPV5',
  );

}